apiVersion: v1
kind: Secret
metadata:
  name: netatmo-exporter-secret
  namespace: netatmo-exporter
type: Opaque
stringData:
  NETATMO_CLIENT_ID: ""
  NETATMO_CLIENT_SECRET: ""
  NETATMO_REFRESH_TOKEN: ""
