apiVersion: apps/v1
kind: Deployment
metadata:
  name: netatmo-exporter
  namespace: netatmo-exporter
  labels:
    app: netatmo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netatmo-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netatmo-exporter
        framework: spring
    spec:
      containers:
        - image: robachmann/netatmo-exporter:1.2.4-arm64
          name: netatmo-exporter
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 512Mi
          env:
            - name: "JAVA_OPTS"
              value: "-XX:ReservedCodeCacheSize=64M -XX:MaxDirectMemorySize=128M"
          envFrom:
            - secretRef:
                name: netatmo-exporter-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 20
