apiVersion: v1
kind: Service
metadata:
  name: netatmo-exporter
  namespace: netatmo-exporter
  labels:
    app: netatmo-exporter
    exporter: netatmo
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  selector:
    app: netatmo-exporter
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP

