apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netatmo-exporter
  namespace: netatmo-exporter
  labels:
    release: prometheus
spec:
  jobLabel: netatmo-exporter
  selector:
    matchLabels:
      exporter: netatmo
  namespaceSelector:
    matchNames:
      - netatmo-exporter
  endpoints:
    - port: http-metrics
      interval: 2m
      path: /metrics
